import DOMPurify, { Config } from "dompurify";
import { storeRef } from "../store/store";

export const allowedHtmlTags = [
	"a",
	"abbr",
	"acronym",
	"address",
	"applet",
	"area",
	"article",
	"aside",
	"audio",
	"b",
	"base",
	"basefont",
	"bdi",
	"bdo",
	"big",
	"blockquote",
	"body",
	"br",
	"button",
	"canvas",
	"caption",
	"center",
	"cite",
	"code",
	"col",
	"colgroup",
	"data",
	"datalist",
	"dd",
	"del",
	"details",
	"dfn",
	"dialog",
	"dir",
	"div",
	"dl",
	"dt",
	"em",
	"embed",
	"fieldset",
	"figcaption",
	"figure",
	"font",
	"footer",
	"form",
	"frame",
	"frameset",
	"h1",
	"h2",
	"h3",
	"h4",
	"h5",
	"h6",
	"head",
	"header",
	"hr",
	"html",
	"i",
	"iframe",
	"img",
	"input",
	"ins",
	"kbd",
	"label",
	"legend",
	"li",
	"link",
	"main",
	"map",
	"mark",
	"meta",
	"meter",
	"nav",
	"noframes",
	"object",
	"ol",
	"optgroup",
	"option",
	"output",
	"p",
	"param",
	"picture",
	"pre",
	"progress",
	"q",
	"rp",
	"rt",
	"ruby",
	"s",
	"samp",
	"section",
	"select",
	"small",
	"source",
	"span",
	"strike",
	"strong",
	"style",
	"sub",
	"summary",
	"sup",
	"svg",
	"table",
	"tbody",
	"td",
	"template",
	"textarea",
	"tfoot",
	"th",
	"thead",
	"time",
	"title",
	"tr",
	"track",
	"tt",
	"u",
	"ul",
	"var",
	"video",
	"wbr",
];

export const allowedHtmlAttributes = [
	"accept",
	"accept-charset",
	"accesskey",
	"action",
	"align",
	"alt",
	"autocomplete",
	"autofocus",
	"autoplay",
	"bgcolor",
	"border",
	"charset",
	"checked",
	"cite",
	"class",
	"color",
	"cols",
	"colspan",
	"content",
	"contenteditable",
	"controls",
	"coords",
	"data",
	"data-*",
	"datetime",
	"default",
	"dir",
	"dirname",
	"disabled",
	"download",
	"draggable",
	"dropzone",
	"enctype",
	"for",
	"form",
	"formaction",
	"headers",
	"height",
	"hidden",
	"high",
	"href",
	"hreflang",
	"http-equiv",
	"id",
	"ismap",
	"kind",
	"label",
	"lang",
	"list",
	"loop",
	"low",
	"max",
	"maxlength",
	"media",
	"method",
	"min",
	"multiple",
	"muted",
	"name",
	"novalidate",
	"open",
	"optimum",
	"pattern",
	"placeholder",
	"poster",
	"preload",
	"readonly",
	"rel",
	"required",
	"reversed",
	"rows",
	"rowspan",
	"sandbox",
	"scope",
	"selected",
	"shape",
	"size",
	"sizes",
	"span",
	"spellcheck",
	"src",
	"srcdoc",
	"srclang",
	"srcset",
	"start",
	"step",
	"style",
	"tabindex",
	"target",
	"title",
	"translate",
	"type",
	"usemap",
	"value",
	"width",
	"wrap",
];

// Hard deny-list: these tags are never permitted regardless of tenant configuration.
// Allowing any of these opens XSS, clickjacking, HTML-injection, or data-exfiltration
// vectors even when ALLOWED_ATTR is otherwise constrained.
// Applied via both FORBID_TAGS (DOMPurify-level, unconditional) and a pre-filter on
// customAllowedHtmlTags (defence-in-depth before DOMPurify is even invoked).
export const ALWAYS_BLOCKED_TAGS = new Set([
	"script",
	"iframe",
	"object",
	"embed",
	"applet",
	"frame",
	"frameset",
	"meta",
	"base",
	"link",
	"style",
	"form",
]);

const config: Config = {
	ALLOWED_TAGS: allowedHtmlTags,
	ALLOWED_ATTR: allowedHtmlAttributes,
	// FORBID_TAGS overrides ALLOWED_TAGS inside DOMPurify — tags listed here are
	// stripped unconditionally, whether the default allow-list or a custom one is used.
	FORBID_TAGS: [...ALWAYS_BLOCKED_TAGS],
};

export const sanitizeHTML = (text: string) => {
	const customAllowedHtmlTags =
		storeRef?.getState().config.settings.widgetSettings.customAllowedHtmlTags;

	let configToUse = config;
	if (customAllowedHtmlTags) {
		// Pre-filter the tenant-supplied list before passing to DOMPurify (defence-in-depth).
		// FORBID_TAGS in the base config already blocks these at the DOMPurify level,
		// but filtering here makes the guarantee explicit and avoids passing dangerous
		// tag names into DOMPurify's ALLOWED_TAGS at all.
		const safeTags = customAllowedHtmlTags.filter(
			tag => !ALWAYS_BLOCKED_TAGS.has(tag.toLowerCase()),
		);
		configToUse = { ...config, ALLOWED_TAGS: safeTags };
	}

	return DOMPurify.sanitize(text, configToUse).toString();
};

export const stripHtmlToInertText = (text: string): string => {
	// 1. strip tags: parse as HTML and keep only the text content
	const stripped = new DOMParser().parseFromString(text, "text/html").body.textContent || "";
	// 2. re-escape so <, >, & render as literal characters and can never
	//    be reinterpreted as markup downstream (robust to nested encoding)
	const escaper = document.createElement("div");
	escaper.textContent = stripped;
	return escaper.innerHTML;
};
