name: Accessibility Test

on: [push, pull_request]

jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start web server
        run: npm run dev &

      - name: Run accessibility tests
        uses: dequelabs/axe-core-action@v1
        with:
          urls: 'http://localhost:8787/'  # Adjust based on your local dev URL
          axe_options: '{ "runOnly": ["wcag2a", "wcag2aa"] }'
